@startuml

group Summary Solicitud de Resumen
Sistema Local -> Repositorio IPS : $Summary
activate Respositorio IPS
Repositorio IPS -> Repositorio IPS : Verifica factibilidad del resumen
Repositorio IPs -> Sistema Local : Emite un Bundle Document o un aviso
 
end

@enduml